# Generated by Django 3.2.6 on 2024-08-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
