# Generated by Django 3.2.6 on 2024-08-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
